import { createHash } from 'node:crypto';
import { readdir, readFile, stat, writeFile } from 'node:fs/promises';
import { relative, resolve } from 'node:path';

const artifactRoot = resolve(process.env.WATER9_SLICE4_ARTIFACT_ROOT
  ?? '/home/orlovboros/artifacts/managers/water9/swimming-backgrounds-full-implementation-2026-07-13/slice4');
const output = resolve(process.env.WATER9_SLICE4_MANIFEST
  ?? 'runs/swimming-backgrounds-full-implementation-2026-07-13/slice4-artifacts.json');
const files = [];

async function walk(directory) {
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const path = resolve(directory, entry.name);
    if (entry.isDirectory()) await walk(path);
    else files.push(path);
  }
}

function classify(path) {
  const relativePath = relative(artifactRoot, path);
  const lower = relativePath.toLowerCase();
  const match = relativePath.match(/b([1-4])-s(\d+)-(\d+)m/);
  const conditions = match ? { biome: Number(match[1]), seed: Number(match[2]), depthMeters: Number(match[3]) } : null;
  if (lower.includes('performance-experiments')) return { role: 'rejected-trace-backed-performance-experiment', acceptedEvidence: false, status: 'REJECTED', conditions };
  if (lower.endsWith('b4-canvas-25s-trace.json')) return { role: 'browser-performance-trace', acceptedEvidence: true, status: 'ACCEPTED_DIAGNOSTIC_GATE_FAIL', conditions: { biome: 4, requestedDepthMeters: 1650, actualDepthMeters: 1650, renderer: 'canvas', warmupMs: 5000, observationMs: 25000 } };
  if (lower.includes('performance-authoritative')) return { role: lower.endsWith('.json') ? 'authoritative-strict-performance-report' : 'authoritative-strict-performance-capture', acceptedEvidence: true, status: 'ACCEPTED_EVIDENCE_GATE_REPORTED_HONESTLY', conditions: { biome: 4, requestedDepthMeters: 1650, actualDepthMeters: 1650, renderer: 'canvas', warmupMs: 5000, observationMs: 25000 } };
  if (lower.includes('performance-trace')) return { role: 'traced-performance-evidence', acceptedEvidence: true, status: 'ACCEPTED_DIAGNOSTIC_GATE_FAIL', conditions };
  if (lower.includes('/recognition/') || lower.startsWith('visual-matrix/recognition/')) return { role: 'hud-free-label-free-anonymous-recognition-card', acceptedEvidence: true, status: 'DECK_ONLY_HUMAN_GATE_OPEN', conditions };
  if (lower.includes('recognition')) return { role: 'anonymous-recognition-deck-metadata', acceptedEvidence: true, status: 'DECK_ONLY_HUMAN_GATE_OPEN', conditions };
  if (lower.includes('/adversarial/') || lower.includes('visual-matrix/adversarial')) return { role: 'normal-play-adversarial-threat-prompt-proof', acceptedEvidence: true, status: 'WORKER_EVIDENCE_MANAGER_ACCEPTANCE_OPEN', conditions };
  if (lower.includes('/normal-play/') || lower.includes('visual-matrix/normal-play')) return { role: 'normal-play-seeded-traversal-proof', acceptedEvidence: true, status: 'WORKER_EVIDENCE_MANAGER_ACCEPTANCE_OPEN', conditions };
  if (lower.endsWith('.json')) return { role: 'measurement-or-provenance-report', acceptedEvidence: true, status: 'ACCEPTED_EVIDENCE', conditions };
  return { role: 'supporting-evidence', acceptedEvidence: true, status: 'ACCEPTED_EVIDENCE', conditions };
}

await walk(artifactRoot);
const artifacts = [];
for (const path of files.sort()) {
  const bytes = (await stat(path)).size;
  const sha256 = createHash('sha256').update(await readFile(path)).digest('hex');
  artifacts.push({ path, relativePath: relative(artifactRoot, path), bytes, sha256, ...classify(path) });
}
const manifest = {
  schema: 'water9/swimming-backgrounds-slice4-artifacts@1',
  generatedAt: new Date().toISOString(),
  artifactRoot,
  provenance: 'Water9 normal-play #game Canvas captures, raw-canvas measurements/cards, browser trace, and focused verification generated by Slice 4 on branch swimming-backgrounds.',
  limitations: ['Worker evidence is not manager visual acceptance.', 'Anonymous deck has zero human reviews; no recognition score is claimed.', 'Performance artifacts preserve honest gate failures.'],
  count: artifacts.length,
  totalBytes: artifacts.reduce((sum, artifact) => sum + artifact.bytes, 0),
  artifacts,
};
await writeFile(output, `${JSON.stringify(manifest, null, 2)}\n`);
console.log(JSON.stringify({ ok: true, output, count: manifest.count, totalBytes: manifest.totalBytes }, null, 2));
