import type { Biome, FishSpecies, FloraSpecies, ShopItem, SubDef, Tile, TileDef, Upgrade } from './types';
import { ANTIVENOM_COST,DYNAMITE_COST,FIRST_AID_COST,FIRST_AID_REPAIR,FLARE_COST,FUEL_TANK_COST,FUEL_TANK_REFILL,INJECTOR_KNIFE_COST,OXYGEN_TANK_COST,OXYGEN_TANK_REFILL,STUN_GRENADE_COST,STUN_GRENADE_DURATION } from './constants';

export const tiles: Record<Tile, TileDef> = {
  water: { color: 0x0b2b38, hp: 0, value: 0, name: 'Water', solid: false },
  sand: { color: 0x745f47, hp: 18, value: 0, name: 'Silt', solid: true },
  stone: { color: 0x4d5564, hp: 42, value: 0, name: 'Basalt', solid: true },
  copper: { color: 0xcf8d55, hp: 34, value: 14, name: 'Copper', solid: true },
  quartz: { color: 0x94e8e3, hp: 40, value: 32, name: 'Quartz', solid: true },
  ruby: { color: 0xe85d75, hp: 52, value: 78, name: 'Ruby', solid: true },
  cobalt: { color: 0x4f8df7, hp: 58, value: 140, name: 'Cobalt Bloom', solid: true },
  sunstone: { color: 0xffb347, hp: 72, value: 310, name: 'Sunstone', solid: true },
  relic: { color: 0xb9f27c, hp: 70, value: 180, name: 'Relic Shard', solid: true },
  drownedIdol: { color: 0xd6fff8, hp: 82, value: 1200, name: 'Drowned Idol', solid: true },
  precursorEngine: { color: 0xffd166, hp: 104, value: 3200, name: 'Precursor Engine', solid: true },
  abyssalCrown: { color: 0xf48cff, hp: 128, value: 7200, name: 'Abyssal Crown', solid: true },
  alienAlloy: { color: 0x73fbd3, hp: 116, value: 520, name: 'Alien Alloy', solid: true },
  ruinCore: { color: 0xffffff, hp: 150, value: 14500, name: 'Ruin Core', solid: true },
  anchorstone: { color: 0x465064, hp: Infinity, value: 0, name: 'Anchorstone', solid: true },
  bedrock: { color: 0x191f2a, hp: Infinity, value: 0, name: 'Bedrock', solid: true },
};

export const upgrades: Upgrade[] = [
  { id: 'oxygen', name: 'O2 Tank', baseCost: 80, max: 5, biome: 1, text: 'Longer dives before returning to the boat.' },
  { id: 'cargo', name: 'Cargo Net', baseCost: 70, max: 5, biome: 1, text: 'Carry more minerals per trip.' },
  { id: 'laser', name: 'Cutting Laser', baseCost: 90, max: 5, biome: 1, text: 'Mine tougher terrain faster.' },
  { id: 'lamp', name: 'Headlamp', baseCost: 60, max: 4, biome: 1, text: 'Pushes back the darkness at depth.' },
  { id: 'scanner', name: 'Scanner', baseCost: 75, max: 4, biome: 1, text: 'Earn more from cataloging sea life.' },
  { id: 'suit', name: 'Pressure Suit', baseCost: 100, max: 4, biome: 1, text: 'More hull and less crash damage.' },
  { id: 'speed', name: 'Diver Jets', baseCost: 85, max: 5, biome: 1, text: 'Increase swim speed and handling.' },
  { id: 'thermal', name: 'Thermal Plating', baseCost: 720, max: 4, biome: 2, text: 'Reduces heat damage from vent fields.' },
];

export const subDefs: SubDef[] = [
  {
    tier: 1,
    name: 'Seeker',
    cost: 18000,
    hull: 360,
    oxygen: 320,
    fuel: 220,
    cargo: 0,
    speed: 168,
    text: 'A compact scout pod. It carries oxygen and armor, moves quickly, and keeps the scanner stable.',
    features: ['Scanner suite', 'High mobility', 'No mining arm'],
  },
  {
    tier: 2,
    name: 'Marlin',
    cost: 62000,
    hull: 680,
    oxygen: 470,
    fuel: 340,
    cargo: 14,
    speed: 150,
    text: 'A working sub with a drill, grabber, reinforced hull, and serious cargo reserves.',
    features: ['Mining drill', 'Ore pickup', 'Harpoon mount'],
  },
  {
    tier: 3,
    name: 'Leviathan',
    cost: 145000,
    hull: 1200,
    oxygen: 720,
    fuel: 520,
    cargo: 28,
    speed: 124,
    text: 'A heavy command sub with weapons, huge endurance, and a bay for a Seeker auxiliary.',
    features: ['Predator weapon', 'Auxiliary Seeker', 'Deep storage'],
  },
];

export const shopItems: ShopItem[] = [
  {
    id: 'stun-grenade',
    name: 'Stun Grenade',
    cost: STUN_GRENADE_COST,
    icon: 'item-icon-stun',
    color: 0x8ee7f4,
    text: `Disorients nearby predators for ${STUN_GRENADE_DURATION} seconds.`,
  },
  {
    id: 'dynamite',
    name: 'Dynamite',
    cost: DYNAMITE_COST,
    icon: 'item-icon-dynamite',
    color: 0xff6f3c,
    text: 'Blasts a compact pocket through mineable stone and ore.',
  },
  {
    id: 'flare',
    name: 'Flare',
    cost: FLARE_COST,
    icon: 'item-icon-flare',
    color: 0xff8a5c,
    text: 'Throws a short-lived light source into the dark.',
  },
  {
    id: 'oxygen-tank',
    name: 'Oxygen Tank',
    cost: OXYGEN_TANK_COST,
    icon: 'item-icon-oxygen-tank',
    color: 0x8ee7f4,
    text: `Emergency reserve that restores ${OXYGEN_TANK_REFILL} oxygen during a dive.`,
  },
  {
    id: 'fuel-tank',
    name: 'Fuel Tank',
    cost: FUEL_TANK_COST,
    icon: 'item-icon-fuel-tank',
    color: 0xffd166,
    text: `Portable cutter fuel that restores ${FUEL_TANK_REFILL} fuel during a dive.`,
  },
  {
    id: 'first-aid-kit',
    name: 'First Aid Kit',
    cost: FIRST_AID_COST,
    icon: 'item-icon-first-aid',
    color: 0xff6f7f,
    text: `Patches ${FIRST_AID_REPAIR} hull integrity and seals active bleeding.`,
  },
  {
    id: 'antivenom',
    name: 'Antivenom',
    cost: ANTIVENOM_COST,
    icon: 'item-icon-antivenom',
    color: 0x7bd88f,
    text: 'Purges venom from suit seals before it can drain you dry.',
  },
  {
    id: 'injector-knife',
    name: 'Injector Knife',
    cost: INJECTOR_KNIFE_COST,
    icon: 'item-icon-stun',
    color: 0xd06bff,
    kind: 'tool',
    text: 'Reusable close-quarters blade. Stab a nearby predator for modest damage.',
  },
];

export const biomeFish: Record<Biome, FishSpecies[]> = {
  1: [
    { species: 'Lantern Fry', count: 22, minY: 100, maxY: 480, color: 0x8ddcf0, hostile: false, pattern: 'school', radius: 8, speed: [34, 58], assetKey: 'fauna-shallow-lantern-fry' },
    { species: 'Snapping Shrimp', count: 18, minY: 120, maxY: 520, color: 0xffb36b, hostile: false, pattern: 'school', radius: 7, speed: [30, 54], assetKey: 'fauna-shallow-snap-shrimp' },
    { species: 'Glass Ray', count: 10, minY: 260, maxY: 880, color: 0xd8f7ff, hostile: false, pattern: 'glide', radius: 15, speed: [18, 32], assetKey: 'fauna-shallow-glass-ray' },
    { species: 'Comb Jelly', count: 12, minY: 180, maxY: 740, color: 0x94e8e3, hostile: false, pattern: 'sway', radius: 11, speed: [14, 26], assetKey: 'fauna-shallow-comb-jelly' },
    { species: 'Reef Squid', count: 11, minY: 360, maxY: 960, color: 0xf2b66d, hostile: false, pattern: 'glide', radius: 10, speed: [26, 44], assetKey: 'fauna-shallow-squid' },
    { species: 'Nautilus', count: 7, minY: 560, maxY: 1280, color: 0xd8c49a, hostile: false, pattern: 'circle', radius: 15, speed: [12, 24], assetKey: 'fauna-shallow-nautilus' },
    { species: 'Moon Jelly', count: 9, minY: 660, maxY: 1500, color: 0xb8f7ff, hostile: false, pattern: 'sway', radius: 13, speed: [10, 20], assetKey: 'fauna-shallow-jellyfish' },
    { species: 'Mantis Shrimp', count: 7, minY: 760, maxY: 1520, color: 0xff6f3c, hostile: true, pattern: 'stalk', radius: 12, speed: [34, 62], assetKey: 'fauna-shallow-mantis-shrimp' },
    { species: 'Blue-ring Octopus', count: 5, minY: 980, maxY: 1860, color: 0xffd166, hostile: true, pattern: 'circle', radius: 14, speed: [18, 34], assetKey: 'fauna-shallow-blue-ring-octopus' },
    { species: 'Tidepool Octopus', count: 6, minY: 1220, maxY: 2180, color: 0xc78065, hostile: false, pattern: 'sway', radius: 17, speed: [14, 28], assetKey: 'fauna-shallow-octopus' },
  ],
  2: [
    { species: 'Ash Minnow', count: 20, minY: 150, maxY: 640, color: 0xffc857, hostile: false, pattern: 'school', radius: 8, speed: [36, 62], assetKey: 'fauna-deep-ash-minnow' },
    { species: 'Deep Sea Shrimp', count: 18, minY: 160, maxY: 620, color: 0xff8a5c, hostile: false, pattern: 'school', radius: 8, speed: [32, 56], assetKey: 'fauna-deep-deep-shrimp' },
    { species: 'Hatchetfish', count: 16, minY: 300, maxY: 900, color: 0xb8f7ff, hostile: false, pattern: 'school', radius: 8, speed: [34, 58], assetKey: 'fauna-deep-hatchetfish' },
    { species: 'Barreleye', count: 10, minY: 520, maxY: 1160, color: 0x7bd88f, hostile: false, pattern: 'circle', radius: 10, speed: [18, 32], assetKey: 'fauna-deep-barreleye' },
    { species: 'Glass Squid', count: 9, minY: 640, maxY: 1400, color: 0x94e8e3, hostile: false, pattern: 'glide', radius: 13, speed: [28, 46], assetKey: 'fauna-deep-glass-squid' },
    { species: 'Vampire Squid', count: 8, minY: 860, maxY: 1680, color: 0xff6f7f, hostile: true, pattern: 'stalk', radius: 14, speed: [34, 60], assetKey: 'fauna-deep-vampire-squid' },
    { species: 'Lanternfish', count: 13, minY: 980, maxY: 1900, color: 0xffd166, hostile: false, pattern: 'glide', radius: 10, speed: [30, 52], assetKey: 'fauna-deep-lanternfish' },
    { species: 'Gulper Eel', count: 6, minY: 1320, maxY: 2260, color: 0xd06bff, hostile: true, pattern: 'stalk', radius: 20, speed: [38, 68], assetKey: 'fauna-deep-gulper-eel' },
    { species: 'Tripodfish', count: 5, minY: 1500, maxY: 2380, color: 0xd8c49a, hostile: false, pattern: 'sway', radius: 18, speed: [10, 22], assetKey: 'fauna-deep-tripodfish' },
    { species: 'Sea Spider', count: 6, minY: 1260, maxY: 2180, color: 0xffc857, hostile: true, pattern: 'circle', radius: 15, speed: [18, 34], assetKey: 'fauna-deep-sea-spider' },
  ],
  3: [
    { species: 'Mirror Fry', count: 18, minY: 160, maxY: 640, color: 0xb8f7ff, hostile: false, pattern: 'school', radius: 8, speed: [42, 72], assetKey: 'fauna-abyss-mirror-fry' },
    { species: 'Hadopelagic Shrimp', count: 15, minY: 180, maxY: 760, color: 0xff8a5c, hostile: false, pattern: 'school', radius: 8, speed: [40, 70], assetKey: 'fauna-abyss-hadal-shrimp' },
    { species: 'Abyssal Jelly', count: 12, minY: 360, maxY: 1040, color: 0xb8f7ff, hostile: false, pattern: 'sway', radius: 14, speed: [12, 24], assetKey: 'fauna-abyss-abyss-jelly' },
    { species: 'Bigfin Squid', count: 8, minY: 620, maxY: 1420, color: 0xff8cb3, hostile: false, pattern: 'glide', radius: 18, speed: [20, 36], assetKey: 'fauna-abyss-bigfin-squid' },
    { species: 'Abyssal Viperfish', count: 10, minY: 660, maxY: 1720, color: 0xff4f90, hostile: true, pattern: 'stalk', radius: 14, speed: [48, 82], assetKey: 'fauna-abyss-viperfish' },
    { species: 'Lantern Swarm', count: 6, minY: 920, maxY: 1900, color: 0xb9a7a0, hostile: false, pattern: 'sway', radius: 22, speed: [10, 22], assetKey: 'fauna-abyss-lantern-swarm' },
    { species: 'Goblin Shark', count: 5, minY: 1240, maxY: 2280, color: 0xff7a8f, hostile: true, pattern: 'stalk', radius: 23, speed: [42, 76], assetKey: 'fauna-abyss-goblin-shark' },
    { species: 'Frilled Shark', count: 5, minY: 1500, maxY: 2460, color: 0xa9b8c9, hostile: true, pattern: 'glide', radius: 24, speed: [34, 62], assetKey: 'fauna-abyss-frilled-shark' },
    { species: 'Black Swallower', count: 4, minY: 1700, maxY: 2580, color: 0x8f8cff, hostile: true, pattern: 'stalk', radius: 27, speed: [34, 66], assetKey: 'fauna-abyss-black-swallower' },
  ],
  4: [
    { species: 'Static Fry', count: 20, minY: 160, maxY: 720, color: 0x73fbd3, hostile: false, pattern: 'school', radius: 8, speed: [44, 76], assetKey: 'fauna-abyss-static-fry' },
    { species: 'Abyssal Hatchet School', count: 18, minY: 180, maxY: 760, color: 0x73fbd3, hostile: false, pattern: 'sway', radius: 18, speed: [10, 18], assetKey: 'fauna-abyss-hatchet-school' },
    { species: 'Abyss Vampire Squid', count: 10, minY: 380, maxY: 1160, color: 0xff6f7f, hostile: false, pattern: 'glide', radius: 14, speed: [24, 42], assetKey: 'fauna-abyss-vampire-squid' },
    { species: 'Hadopelagic Microfish', count: 8, minY: 520, maxY: 1440, color: 0xb9a7a0, hostile: false, pattern: 'sway', radius: 24, speed: [10, 20], assetKey: 'fauna-abyss-microfish' },
    { species: 'Anglerfish', count: 12, minY: 640, maxY: 1740, color: 0xffd166, hostile: true, pattern: 'stalk', radius: 16, speed: [42, 74], assetKey: 'fauna-abyss-anglerfish' },
    { species: 'Viperfish', count: 10, minY: 840, maxY: 1980, color: 0xb8f7ff, hostile: true, pattern: 'stalk', radius: 15, speed: [52, 88], assetKey: 'fauna-abyss-snipe-eel' },
    { species: 'Goblin Shark', count: 6, minY: 1240, maxY: 2360, color: 0xff7a8f, hostile: true, pattern: 'glide', radius: 24, speed: [44, 78], assetKey: 'fauna-abyss-goblin-shark' },
    { species: 'Black Swallower', count: 5, minY: 1540, maxY: 2600, color: 0x8f8cff, hostile: true, pattern: 'stalk', radius: 30, speed: [38, 70], assetKey: 'fauna-abyss-black-swallower' },
    { species: 'Abyssal Medusa', count: 8, minY: 1640, maxY: 2680, color: 0xb8f7ff, hostile: false, pattern: 'circle', radius: 16, speed: [10, 22], assetKey: 'fauna-abyss-medusa' },
  ],
};

export const biomeFlora: Record<Biome, FloraSpecies[]> = {
  1: [
    { species: 'Glass Kelp', count: 18, minY: 180, maxY: 820, color: 0x7bd88f, hazardous: false, rare: false, radius: 12 },
    { species: 'Moon Sponge', count: 10, minY: 420, maxY: 1180, color: 0x94e8e3, hazardous: false, rare: false, radius: 11 },
    { species: 'Sting Anemone', count: 4, minY: 760, maxY: 1440, color: 0xff6f7f, hazardous: true, rare: true, radius: 14 },
  ],
  2: [
    { species: 'Brine Grass', count: 20, minY: 200, maxY: 900, color: 0xb9f27c, hazardous: false, rare: false, radius: 11 },
    { species: 'Vent Coral', count: 10, minY: 620, maxY: 1560, color: 0xff8a5c, hazardous: true, rare: false, radius: 15 },
    { species: 'Ember Bloom', count: 5, minY: 960, maxY: 1860, color: 0xffd166, hazardous: true, rare: true, radius: 16 },
  ],
  3: [
    { species: 'Black Fan', count: 18, minY: 220, maxY: 980, color: 0x9a8cff, hazardous: false, rare: false, radius: 13 },
    { species: 'Needle Garden', count: 12, minY: 640, maxY: 1680, color: 0xff5d8f, hazardous: true, rare: false, radius: 16 },
    { species: 'Crown Polyp', count: 4, minY: 1200, maxY: 2200, color: 0xffd166, hazardous: true, rare: true, radius: 18 },
  ],
  4: [
    { species: 'Circuit Kelp', count: 18, minY: 260, maxY: 1120, color: 0x73fbd3, hazardous: false, rare: false, radius: 13 },
    { species: 'Glass Obelisk', count: 10, minY: 820, maxY: 1880, color: 0xb8f7ff, hazardous: true, rare: false, radius: 18 },
    { species: 'Oracle Polyp', count: 5, minY: 1420, maxY: 2480, color: 0xf48cff, hazardous: true, rare: true, radius: 20 },
  ],
};
